### ISSUE TITLE
Link PerformanceEntry in IDL

### ISSUE THREAD

**Issue by annevk** [w3c/resource-timing#107]
That makes it much easier to read the IDL. This is common practice in other standards. Consider using https://github.com/tabatkins/bikeshed as it makes this automatic.

**Comment by yoavweiss** [comment]
Looking into this, I think that ReSpec is also supposed to do the same automatically.
Talking to @tobie, [seems like](https://twitter.com/tobie/status/997108639503732737) this is something @tabatkins or @plinss might be able to help with.

**Comment by tabatkins** [comment]
No, that's a cross-spec link, which ReSpec is unable to do.

**Comment by tabatkins** [comment]
To elaborate: ReSpec, being a client-side solution, is incapable of doing cross-spec linking, because doing so requires either downloading a multi-MB linking database (like Bikeshed has), or setting up a server that can respond to linking queries and tell the script what to link to.  The former is obviously unworkable; the latter is theoretically possible, but nobody's ever done it, and it would mean hitting the server every single time someone views the spec.

You really should be using Bikeshed, and as this is only a 1k-long spec, the conversion would be quick and easy. Glad to help with that if you want.

**Comment by marcoscaceres** [comment]
You can just `<dfn data-cite=spec#frag>Thing</dfn>` in ReSpec. Happy to help also.

**Comment by tabatkins** [comment]
Hm, that requires manually marking up your IDL fragments, tho.

**Comment by marcoscaceres** [comment]
No, one adds the dfn outside the IDL. I’ll send a PR.
