### ISSUE TITLE
NextHopProtocol Values

### ISSUE THREAD

**Issue by googUser** [w3c/resource-timing#122]
I'm investigating the nextHopProtocol (https://w3c.github.io/resource-timing/#dom-performanceresourcetiming-nexthopprotocol), and I need to know what possible values it can have. According to ALPN Protocol ID [RFC7301] (https://tools.ietf.org/html/rfc7301#section-6), it appears that the set of possible values is "http/1.1", "spdy/1", "spdy/2", and "spdy/3". To test this, I went on several websites and examined the nextHopProtocol value by entering performance.getEntriesByType('navigation')[0].nextHopProtocol into the JS console. I found some instances of "http/1.1" (e.g. on https://go.twitch.tv/, https://www.apple.com/), but I also found "hq" (e.g. on https://www.google.com/, the new tab page) and "h2" (e.g. on https://twitter.com, https://www.reddit.com/).

From the spec, it's not clear what "hq" or "h2" mean. It would also be beneficial to have a master list of all possible values that the nextHopProtocol can be.

And for the record, I did this investigation on a Mac using Chrome Version 63.0.3230.0 (Official Build) dev (64-bit).

**Comment by toddreifsteck** [comment]
@igrigorik Adding to this, there are parts of the alpnID for token binding that should not appear in nextHopProtocol. We probably need to make this a whitelist of strings.... Lets talk about this on 10/26.

**Comment by igrigorik** [comment]
Courtesy of @plehegar: https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids

**Comment by plehegar** [comment]
Note that the registry doesn't contain the "hq" value, so #125 doesn't fully answer the question.

**Comment by toddreifsteck** [comment]
Per discussion at TPAC, add HTTP/1.0 by following up with Ryan Sleevi/Ryan Hamilton from Chrome. Also, add a MAY for exposing experimental ALPN fields that are not in the registry.

**Comment by plehegar** [comment]
( @sleevi , @RyanAtGoogle )

**Comment by sleevi** [comment]
@plehegar @toddreifsteck Could you clarify? I'm trying to understand if this is related to https://bugs.chromium.org/p/chromium/issues/detail?id=780640

Namely, the following possible values are returned by Chromium today:
* hq
* http/0.9
* http/1.0
* http/1.1
* h2
* spdy/3 (Note: legacy value related to cached entries)

Given that the Registry is "Expert Review", it seems like there is considerably less friction for registering, so it does not seem wise or advisable to allow such exposure prior to registration, even for informational/experimental I-Ds. This was a point of discussion with respect to QUIC's exposure as well (hence the "hq"), but it would be unfortunate if that was established as the new norm.

With respect to the other items, this requires following the IANA registration process. I'm not sure why the follow-up tagging @RyanAtGoogle and myself - @igrigorik was handling that :)

**Comment by RyanAtGoogle** [comment]
I'm not sure I understand what question I can answer/comment on. Can you clarify?

**Comment by yoavweiss** [comment]
Decided on the call: We'll add normative text to the spec that implementations MAY add "HTTP/0.9". ALPN already covers 1.0 and the QUIC RFC already adds "hq" to the registry.

**Comment by MikeBishop** [comment]
...except that as it's not an RFC yet, it's not registered with IANA yet.

**Comment by yoavweiss** [comment]
For QUIC, we can point to https://tools.ietf.org/html/draft-ietf-quic-http-11#section-9.1 explicitly. We'd change it once it hits RFC status.

I'm failing to find the HTTP/1.0 definition though. Worst case we can add a note regarding both HTTP/0.9 and HTTP/1.0, but if someone remembers where that definition that we discussed on the call was, that'd be better...

**Comment by igrigorik** [comment]
> I'm failing to find the HTTP/1.0 definition though. Worst case we can add a note regarding both HTTP/0.9 and HTTP/1.0, but if someone remembers where that definition that we discussed on the call was, that'd be better...

No such thing exists. We filed a bug against http-wg and they came back with "write an RFC". FWIW, I'm OK with just making a recommendation in RT spec, as you've done in your PR.

**Comment by MikeBishop** [comment]
Formally, since it's Expert Review and not IETF Action, I think we could submit a registration.  There has to be a pointer to a specification, but the specification isn't required to do the registering or to be an RFC.  Just e-mail IANA.

**Comment by LPardue** [comment]
A conceptual problem here comes from the sentence

> The registry for protocol identifiers lists the possible values for the ALPN Protocol IDs

Only some of the IDs will be registered, endpoints are free to negotiate non-registered protocols, and it seems like nextHopProtocol can fall short of reporting what is actually happening..

The prime example is HTTP/QUIC experimentation where the endpoints will want to test hq-nn (where nn is a draft number).

**Comment by yoavweiss** [comment]
@LPardue - Can you take a look at the current PR text with regard to experimental protocols? https://github.com/w3c/resource-timing/pull/159

**Comment by LPardue** [comment]
Thanks @yoavweiss. The PR says:

> In case the user agent is using an experimental protocol which ALPN protocol ID has not yet been defined in the above registry, the user agent MAY use another descriptive string.

This text reads slightly ambiguously to me, as a application/server experimenter I'd really like the UA to report the actual negotiated ALPN, not some arbitrary string. (For context, at one point Chrome was mistakenly reporting one of my sites was offering "hq" just because it was HTTP over QUIC. This got fixed, thanks!).

So I might rewrite this and some of the preceeding text as:

__The registry for protocol identifiers lists the possible values for the <a href="https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids">ALPN Protocol IDs</a>. For the HTTP/0.9 and HTTP/1.0 network protocols, which are not defined in the ALPN Protocol ID registry, user agents MAY return "http/0.9" and "http/1.0" respectively. In case the user agent is using an experimental protocol which ALPN protocol ID has not yet been defined in the above registry, the user agent MAY use another descriptive string._

_Formally registered ALPN Protocol IDs are documented by <a href="https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids">IANA</a>. HTTP/0.9 and HTTP/1.0 network protocols are notably absent from this registry. Where a user agent negotiates one of these protocols it MAY return the value "http/0.9" or "http/1.0" respectively. Note that values MUST be percent-encoded as described above._

_<p class=note>The "hq" ALPN ID is defined for the final version of the HTTP over QUIC protocol, as described in the <a href="https://tools.ietf.org/html/draft-ietf-quic-http-11#section-9.1">HTTP over QUIC Internet Draft</a>.</p>_

_User agents MAY negotiate experimental, non-registered network protocols. In such cases, the user agent SHOULD provide the negotiated value. However, it MAY use any other descriptive string._

**Comment by yoavweiss** [comment]
> User agents MAY negotiate experimental, non-registered network protocols. In such cases, the user agent SHOULD provide the negotiated value. However, it MAY use any other descriptive string.

That actually doesn't cover the GQUIC case, which is not ALPN-negotiated AFAIK. Maybe a mix of both to cover both that and potential future protocols which are ALPN-negotiated but not yet registered.

**Comment by LPardue** [comment]
Hmm yeah, GQUIC is advertised with Alt-Svc (using 'quic') but "negotiated" by trying out UDP connectivity and then performing a QUIC crypto handshake.

The wider reuse of ALPN IDs for different purposes is muddling.

Perhaps a better term is "User agents MAY select registered or non-registered network protocols".

**Comment by LPardue** [comment]
I would prefer a SHOULD for the negotiated value (if present) but won't argue strongly if people disagree.

**Comment by yoavweiss** [comment]
Changed to SHOULD. Let's see what people say.

**Comment by MikeBishop** [comment]
Honestly, I'd go even stronger -- if ALPN was used, this MUST be the actual ALPN token, registered or not.  If ALPN was not used, a descriptive string for the protocol (which might or might not be an ALPN token) MAY be supplied instead.

**Comment by igrigorik** [comment]
sgtm

**Comment by RyanAtGoogle** [comment]
+1. That text sounds ideal.

**Comment by MikeBishop** [comment]
And let's side-step the discussion of HTTP/0.9 and HTTP/1.1 by just registering the tokens.  I'll take the action item to e-mail IANA and copy @yoavweiss and @igrigorik.

**Comment by yoavweiss** [comment]
@MikeBishop Thanks for emailing IANA! :)
I'll update the text, assuming they'd accept the registration

**Comment by MikeBishop** [comment]
Registration for 0.9 & 1.0 has been added - https://www.iana.org/assignments/tls-extensiontype-values.
