### ISSUE TITLE
Are fetchStart, connectStart, redirectStart relative to navigationStart?

### ISSUE THREAD

**Issue by Nithanaroy** [w3c/resource-timing#237]
Times like fetchStart, connectStart, redirectStart are not timestamps to compare with page level metrics like loadEventEnd. Are they relative to navigationStart?

**Comment by npm1** [comment]
What's loadEventEnd? But yes, the values returned in the API are relative to the timeOrigin (so yea, navigationStart).

**Comment by Nithanaroy** [comment]
Okay. Thank you. 
I'm referring to https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming/loadEventEnd

The numbers I'm seeing in our [RUM](https://developer.mozilla.org/en-US/docs/Web/Performance/Rum-vs-Synthetic#Real_User_Monitoring) datasets are weird based on the definition you confirmed. I am seeing
```
loadEventEnd - navigationStart < postOnLoadResourceTimingEntry.startTime
```
for a lot of RUM samples.
Here `postOnLoadResourceTimingEntry` is a resource that is initiated on the page's `onLoad` event.

Any thoughts on why this could be happening?

**Comment by npm1** [comment]
How much bigger is it? I would suggest looking at performance.timeOrigin, how different is it from navigationStart? The former is the one used for startTime, and also we jitter the values so that could affect this kind of comparison. Also worth double checking that the fetch begins directly on onLoad and not in a promise inside it, or something like that which introduces some delay.

**Comment by nicjansma** [comment]
Do you have a page that reproduces this problem?  Have you seen this across browsers, or only in specific ones?

> Here postOnLoadResourceTimingEntry is a resource that is initiated on the page's onLoad event.

In that case, the `loadEventEnd` hasn't happened yet (since the handler is still running), so it's likely the `postOnLoadResourceTimingEntry.startTime` should happen prior to `loadEventEnd-navigationStart`.  If you compare to `loadEventStart`, `postOnLoadResourceTimingEntry.startTime` should be after that.

If that's not the issue, there are a few known browser bugs with `navigationStart` (via NavigationTiming) and `timeOrigin` (which ResourceTiming use) differing slightly https://bugs.chromium.org/p/chromium/issues/detail?id=955532#c26

**Comment by Nithanaroy** [comment]
Hi @npm1,
On my dev machine it happens around 100ms earlier, but on users' devices I have seen bigger numbers. Both `timeOrigin` and `navigationStart` match for the page I'm interested in.
![Screen Shot 2020-11-11 at 1 29 10 PM](https://user-images.githubusercontent.com/670556/98866621-15e8d300-2422-11eb-983e-ff3903826a51.png)

And I verified the code to make the resource we are fetching happens on the onLoad event of the window, something like,
```javascript
window.addEventListener('load', () => { getMyApiDataUsingFetch(); });
```

**Comment by npm1** [comment]
One additional idea: locally you could log performance.now() at the beginning and at the end of the load event to know the time frame where we were expecting the fetch to begin. That said, fetching is inherently asynchronous in modern browsers, so I'm not surprised that this happens in some cases. That is, the process that runs the JavaScript is not the same as the process which performs the network requests, so this could explain why you may see this kind of result, unless you use an async function and await the fetch.

**Comment by Nithanaroy** [comment]
Hi @nicjansma,
I think with `loadEventStart` the numbers look reasonable, i.e.
```
loadEventStart - navigationStart < postOnLoadResourceTimingEntry.startTime
```
Is `loadEventEnd - loadEventStart` the time taken to execute the `onLoad` event handler? Are these separated to easily see how much work is being immediately after page load?

Thanks for all the ideas @npm1 :)

**Comment by nicjansma** [comment]
Correct `loadEventEnd` is the timestamp before the `onload` handlers run and `loadEventStart` is the timestamp after all `onload` handlers have finished, so the difference between the two is the duration.

If you're executing code at `onload`, any network requests that start then will probably have a `startTime` after` loadEventStart` and before `loadEventEnd`

**Comment by nicjansma** [comment]
@Nithanaroy I believe we've addressed your issue, but please leave a comment if there is still a question here!

**Comment by Krinkle** [comment]
> `loadEventEnd` is the timestamp before the `onload` handlers run and `loadEventStart` is the timestamp after all `onload` handlers have finished, […]

I think you meant the other way around, right? 🙂
