### ISSUE TITLE
onresourcetimingbufferfull: EventHandler or GlobalEventHandler?

### ISSUE THREAD

**Issue by AFBarstow** [w3c/resource-timing#49]
Why is onresourcetimingbufferfull an EventHandler on the Performance object rather than a GlobalEventHandler?

**Comment by plehegar** [comment]
Sorry to ask but, got a pointer to GlobalEventHandler?

**Comment by AFBarstow** [comment]
https://html.spec.whatwg.org/#globaleventhandlers

**Comment by plehegar** [comment]
Thanks Art. It isn't clear to me that we considered it. Closest I can find was
 https://lists.w3.org/Archives/Public/public-web-perf/2013Sep/0026.html
but that doesn't answer this issue.
Now, I don't think we have a use case to fire resourcetimingbufferfull on elements. We associate the performance object to the global one (http://w3c.github.io/hr-time/#idl-def-globalperformance) so we could consider firing it to the window object instead of the performance object. Not sure what the recommendations are there however. Although, I wonder if that choice sailed too long ago for us to change it at this time.

**Comment by AFBarstow** [comment]
I was thinking of setting it on, f.ex. <body> but it's not much additional work to set peformance.on... directly. And since the ship has sailed on this, I'll close it. Thanks for the quick repy!

**Comment by AFBarstow** [comment]
(the f.ex. above was the body element which the comment widget apparently ate ;-))
