### ISSUE TITLE
transferSize and TAO redirects

### ISSUE THREAD

**Issue by yoavweiss** [w3c/resource-timing#61]
A couple of weird things spotted while reviewing Blink's implementation docs:

> the size, in octets received from a HTTP-network fetch, consumed by the response header fields and the response payload body [RFC7230] if the last non-redirected fetch of the resource passes the timing allow check algorithm.

"last" here seems spurious and confusing. If we have a redirection chain, we can expose the size if the final resource fetch passes TAO checks. Unless I'm missing some weird scenario, that would be the first, last and only non-redirected fetch in that chain.

> If there are HTTP redirects or equivalent when navigating and if all the redirects or equivalent are from the same origin [RFC6454], this attribute should include the HTTP overhead of incurred redirects

Is there a particular reason we don't expose the redirection overhead of TAO-enabled redirects? I think we should, unless some security considerations dictate otherwise.

**Comment by igrigorik** [comment]
Re, "last": yes, I think we could drop that but I'm not sure it's a big deal. For RT{1,2} we're not exposing each individual fetch so I think there is still value in clarifying this behavior. Once we address https://github.com/w3c/resource-timing/issues/21, I think it'll be definitely redundant.

Re, TAO-enabled redirects: if memory serves, I think the complication was with respect to what happens when some redirects have the opt-in and some don't.. because we don't expose which is which it becomes hard to reason about the returned number; so we opted to do all-or-nothing.

**Comment by igrigorik** [comment]
Re-reading the spec.. Re, "last": I believe this is fine, we're just being explicit about allowing transferSize to be exposed when the last non-redirected fetch passes TAO; this language is consistent with the rest of the spec.

That said, I'm not sure why we restricted the redirect chain case to same-origin only.. The check that we want is that all redirects have TAO opt-in -- i.e. same as all other attributes. I'll push a change to fix that.
