### ISSUE TITLE
Exposing CSS subresource URLs

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/resource-timing#70]
See https://github.com/w3c/resource-timing/issues/27

**Comment by plehegar** [comment]
The specific test needs to test for resource exclusion:
"For each resource fetched by the current browsing context, **excluding resources fetched by cross-origin stylesheets fetched with no-cors policy,**"

**Comment by toddreifsteck** [comment]
Adding @yoavweiss  as assignee per call on 1/18/2018.

**Comment by yoavweiss** [comment]
Submitted a test PR, but all browsers I tested in seem to be failing it in one way or another.(Admittedly, didn't test Edge...)

**Comment by yoavweiss** [comment]
As it seems like browsers expose this information right now, as well as intending to expose it per spec through Service Workers, I'm not sure what the reasoning is to bar that information from Resource Timing.

Note that there are several major use cases for this info (e.g. measuring loading of Google Fonts).

**Comment by yoavweiss** [comment]
This is blocked by https://github.com/w3c/ServiceWorker/issues/719

**Comment by yoavweiss** [comment]
I don't see implementer interest in aligning to the spec in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=532399

Unless other implementers feel otherwise and want to change their current implementations, I feel we should align the spec to the implementations, and remove the "excluding resources fetched by cross-origin stylesheets fetched with no-cors policy" language.

@toddreifsteck @rniwa @digitarald - thoughts?

**Comment by toddreifsteck** [comment]
I generally agree with @yoavweiss 's conclusion

**Comment by yoavweiss** [comment]
@past - thoughts from Mozilla?

**Comment by annevk** [comment]
Yeah.

**Comment by annevk** [comment]
I'm a bit appalled I wasn't asked for input on this directly given that I raised the security issue to begin with... Seems rather disingenuous.

**Comment by igrigorik** [comment]
Let's keep this collaborative. I don't believe there are any disingenuous intentions here on anyones behalf.  This is a long-outstanding issue that (a) is tied to https://github.com/w3c/ServiceWorker/issues/719 that everyone on this thread has been trying to help resolve and nudge along. In absence of clear signals on that thread and in light of feedback in https://bugs.chromium.org/p/chromium/issues/detail?id=532399, I think the raised proposal to remove this wording from RT is worth considering.

If we feel strongly that the SW-exposure is a bug, can we prioritize the work to resolve that in Fetch?

**Comment by annevk** [comment]
@igrigorik it's not an issue with Fetch as far as I know. One issue is that CSS doesn't define how it fetches. And one issue is that resource timing is not grounded in web platform architecture and therefore it's unclear how it works.

**Comment by yoavweiss** [comment]
@annevk the folks I included in my latest message were mostly WebPerfWG folks which were largely present in our latest discussion on this. I missed the fact that you initiated the original security issue, so failed to include you directly.

FWIW, I'm not suggesting here that this issue is not important and should not be solved. I already [created the test](https://github.com/w3c/web-platform-tests/pull/9307) for it.

At the same time, this SOP hole has been open for the last ~6 years with Resource Timing, and for the last ~3 with Service Workers. This is true for all implementing browsers, so all modern ones. (as well as some not-so-modern ones).
Browser implementations don't seem interested in solving this issue, and on my end, I agree that it makes no sense to cripple one API if the info is happily exposed on another.

So, I suggest to remove the relevant spec language from ResourceTiming, and align the spec with the shipped reality of the web. If at some point the Service Worker [issue](https://github.com/w3c/ServiceWorker/issues/719) will be resolved, we can easily bring back that spec language as well as the tests, and more importantly, implement the restriction.

> In particular, I still don't think anyone has proposed a solution that completely handles the various @imports cases. I raised this back in w3c/ServiceWorker#719 (comment).

@wanderview - indeed the various import cases will need to be better defined in RT as well if we decide to keep the restriction.

**Comment by annevk** [comment]
@yoavweiss https://bugzilla.mozilla.org/show_bug.cgi?id=1180145 suggests it's fixed in Firefox as far as Resource Timing is concerned. The last time Chrome's security team said something in public about this they also wanted to fix this. Has that changed?

We keep running into new security issues with "no-cors", Spectre being a pretty recent and bad case of that. I think we need a much more compelling reason to enshrine SOP violations into the platform than nobody having bothered to fix their issues (which isn't completely true as far as Firefox is concerned).

**Comment by yoavweiss** [comment]
Firefox is failing the related WPT test, but looking deeper, it does seem like only the font is exposed, while the image is not...

**Comment by annevk** [comment]
Ah, that's tracked by https://bugzilla.mozilla.org/show_bug.cgi?id=1423602.

**Comment by yoavweiss** [comment]
OK, great! Is there interest from Firefox to tackle the SW piece as well? Any timelines on that front you can share?

**Comment by annevk** [comment]
We are interested, but as we stated in the relevant issue we want to coordinate deployment with other browsers to take the compat risk together.

**Comment by rniwa** [comment]
I don't think we should expose timing information on no-CORS resources. We should fix the service worker not to expose this information if that's the case.

But could someone give me a pointer describing the issue in the service worker? I can't find any information as to how service worker is exposing the same timing information as resource timing API for non-CORS cross-origin resources.

**Comment by yoavweiss** [comment]
@rniwa this is not about exposing timing information beyond what TAO allows, but about exposing the URLs of resources loaded by no-cors fetched CSS.
The related SW issue is https://github.com/w3c/ServiceWorker/issues/719

**Comment by rniwa** [comment]
Okay, exposing URL is bad but exposing the timing of non-CORS cross-origin resources is also bad. That could lead to timing attacks on server-side processing time.

**Comment by yoavweiss** [comment]
@rniwa timing for cross-origin resource (CORS or non-CORS) is only exposed if the origin explicitly opts into that, using the Timing-Allow-Origin headers.
Obviously, servers should not opt-in to exposing their timing if it can reveal something about the user's state or other info which may be used to exploit them.

This issue however is focused on exposing the URLs fetched by non-CORS CSS fetches. Fixing that would mean:
* These URLs don't create Resource Timing entries - this is the current state of the spec, but not the current state of most implementations. Firefox are now in the process of fixing that in their implementation.
* The requests don't get intercepted by Service Workers - this is not currently specified nor implemented, and AFAICT there's no consensus regarding that.

**Comment by yoavweiss** [comment]
Note that a decision here would also impact Server Timing, which [processing model](https://w3c.github.io/server-timing/#processing-model) also includes that exclusion of no-cors CSS loaded subresources.

**Comment by yoavweiss** [comment]
This issue was discussed at the latest call ([minutes](https://www.w3.org/2018/08/20-webperf-minutes.html#item05)). 
We agreed that URL and timing info for CSS subresources is not exposed beyond what SW already exposes. We also agreed that as long as SWs continue to expose that information, hiding it from RT makes little sense.

Consensus on the call (Including folks from Chrome, Edge, WebKit, but unfortunately not Firefox) was to remove the language relating to cross-origin CSS subresources from the spec, until a time where this restriction is enforced by the Service Workers spec and its implementations.

**Comment by annevk** [comment]
I don't really see any new information there that would warrant a change in position.

**Comment by yoavweiss** [comment]
@annevk the rational behind the decision is that RT doesn't expose anything that SW isn't already exposing. Once SWs change their behavior, RT will follow. But the current aspirational spec language does not match most RT implementations, and does not make sense in light of the SW situation.

Looking at your [past comment](https://github.com/w3c/resource-timing/issues/70#issuecomment-391701893):

> We are interested, but as we stated in the relevant issue we want to coordinate deployment with other browsers to take the compat risk together.

Have you had any traction with that? Is there reason to believe the situation will change in the near future?

**Comment by annevk** [comment]
I don't think rationale of the type "we have a security hole in A so it's acceptable to have the same hole in B" is compelling. Especially since you plan on reverting if the hole is closed in A. You'll just end up making that harder.

**Comment by yoavweiss** [comment]
My understanding is that:

1. There's disagreement that exposing cross-origin CSS subresource URLs is indeed a security hole, and assuming it is, there's disagreement regarding its severity.
2. As a result, there's lack of implementer appetite to resolve this issue.
3. A "fix" for this was [added](https://github.com/w3c/resource-timing/issues/27) to the RT spec, but largely not implemented in the 3 years since. I appreciate that Firefox made some progress on that [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1423602), but it still doesn't pass the related [tests](https://github.com/web-platform-tests/wpt/pull/9307).
4. Even if all implementers would now implement the restriction for RT, users will still have that information exposed in SW in all implementations.
5. The [SW issue](https://github.com/w3c/ServiceWorker/issues/719) have been open for over 3 years, and haven't seen any movement in the last ~7 months.
6. In the current state, we cannot ship Resource-Timing to L2, as the aspirational CSS subresource limitation doesn't represent the feature implementations that are out there.

Do you disagree on any of the points above? Do you predict the SW situation to change in the near future?

If the answer to the above questions is "no", keeping this restriction in RT basically means holding the feature hostage for the foreseeable future. During the last call, the group agreed that this is not desirable.

**Comment by annevk** [comment]
I disagree with the coupling with service workers. I also continue to be surprised that this means you cannot ship, whereas defining the feature without grounding in primitives (i.e., Fetch) is totally fine.

**Comment by rniwa** [comment]
I think we need to unexposed non-CORS cross-origin CSS requests from resource timing. If the implementation is the only thing that's holding back, then I'd say we're willing to make the code change in WebKit.

**Comment by yoavweiss** [comment]
@rniwa I thought we agreed on the call that as long as this information is exposed in SW, it doesn't make sense to unexpose it in RT. Are you suggesting that you'd be willing to make implementation progress on unexposing it in SW?

**Comment by rniwa** [comment]
Yes, we should simply fix service workers now that we're aware of the issue. Meanwhile, there is no need to introduce a new security problem into resource timing specification. We should be fixing the implementations instead.

**Comment by yoavweiss** [comment]
@youennf - any news on that front following our [TPAC breakout session](https://www.w3.org/2018/10/24-csssop-minutes.html)?

**Comment by youennf** [comment]
@yoavweiss, we plan to fix the resource timing as soon as possible.

**Comment by yoavweiss** [comment]
> @yoavweiss, we plan to fix the resource timing issue as soon as possible.

As well as service workers?

**Comment by youennf** [comment]
> > @yoavweiss, we plan to fix the resource timing issue as soon as possible.
> 
> As well as service workers?

We also want to fix this and are discussing the best way to proceed.
Ideally there should be a way for web developers to import CSS stylesheets using CORS.

**Comment by yoavweiss** [comment]
> Ideally there should be a way for web developers to import CSS stylesheets using CORS.

Maybe the request mode should be transitive for CSS imports?

**Comment by domenic** [comment]
We did something similar for JS modules, whose credentials mode can be controlled at top level via an attribute on the script element, but then propagates to all imports in the graph (in an automatic way that cannot be controlled).

**Comment by youennf** [comment]
Yep, that would also be my preferred option, but I do not know how much breakage that would cause. Any insight?

**Comment by yoavweiss** [comment]
> Yep, that would also be my preferred option, but I do not know how much breakage that would cause. Any insight?

That would break in cases where the initial CSS is fetched with a `crossorigin` attribute, but the import is not. That seems like something the HTTPArchive may be able help with. (One query to gather CORS requested CSS that has `@import`, and another to see how much of those URLs are CORS enabled.)

/cc @rickviscomi

**Comment by youennf** [comment]
Resource timing leakage is now fixed in WebKit ToT, https://bugs.webkit.org/show_bug.cgi?id=192132.

> That would break in cases where the initial CSS is fetched with a `crossorigin` attribute, but the import is not. That seems like something the HTTPArchive may be able help with. (One query to gather CORS requested CSS that has `@import`, and another to see how much of those URLs are CORS enabled.

Having a list of cross-origin imported CSS would be definitely useful.
I do not think HTTPArchive will tell us whether these URLs are CORS enabled though (no Origin header in the corresponding request probably).
Once we have the list, we should be able to curl them to check that.

**Comment by yoavweiss** [comment]
> I do not think HTTPArchive will tell us whether these URLs are CORS enabled though (no Origin header in the corresponding request probably).

The HTTPArchive also includes the request headers, so you could detect CORS enabled requests from the existence of the `Origin` header.

> Once we have the list, we should be able to curl them to check that.

To be clear, I don't think I'll have the bandwidth to tackle this is the near future. I just pointed out that the data set to perform this analysis exists and is publicly available.

**Comment by yoavweiss** [comment]
Trying to think how to unblock L2 from this discussion, on which there's no clear agreement and which requires further research and spec work.

I suggest (again) to ship L2 without this restriction, which represents a majority of implementations today, and reintroduce that restriction to L3 if and when implementations actually introduce it and once there's consensus on that front.

@toddreifsteck @igrigorik - thoughts?

**Comment by toddreifsteck** [comment]
It seems that everyone agrees this is a privacy hole, but the disagreement is in the priority of the privacy hole given that Service Worker has the same hole and appears less apt to fix.

Given that, why don't we update the spec to state that this is an At-Risk piece of the spec and ship L2 with that note?

That leaves the intent of the spec in place, but allows us to remove the normative requirement.

As discussed in a sync of the chairs, if 2 implementations are able to quickly pass the tests, it is a quick patch to make this a requirement.

@igrigorik  @yoavweiss How is that?

**Comment by yoavweiss** [comment]
Landed the related tests in https://github.com/web-platform-tests/wpt/pull/9307
Leaving this open until we have 2 passing implementations

**Comment by youennf** [comment]
> As discussed in a sync of the chairs, if 2 implementations are able to quickly pass the tests, it is a quick patch to make this a requirement.

STP72 passes the test, Firefox is just missing the font one. The 2 implementations criteria is very close.
IIUC, L2 is a WD and might migrate to CR soon.
Since there is consensus in the behavior we want, I would specify the change before CR as way to encourage implementers to align.

**Comment by yoavweiss** [comment]
To be clear, the current spec includes the resource exclusion (step 1 in the [processing model](https://w3c.github.io/resource-timing/#processing-model)). So the question here was whether we should keep that exclusion or not. Assuming Firefox will align and pass the test, I agree it makes sense to keep the exclusion for L2.

If Firefox doesn't align in time, we can indeed mark this "at risk", as @toddreifsteck suggested.

**Comment by igrigorik** [comment]
FWIW, given that we agree on the behavior and tests are in place, I don't think we need to keep this open. Rather, let's update https://github.com/w3c/resource-timing/issues/70 with the outstanding requirements we need to hit to move L2 to CR?

**Comment by igrigorik** [comment]
@toddreifsteck sorry, missed your earlier comment. I'm OK with adding an at-risk note, which we can remove as soon as we have to green implementations.
