### ISSUE TITLE
Increase limit of 150 for PerformanceEntrys?

### ISSUE THREAD

**Issue by nolanlawson** [w3c/resource-timing#89]
The spec says:

> The recommended minimum number of PerformanceResourceTiming objects is 150, though this may be changed by the user agent

I tested Chrome 55, Firefox 50, Edge 14, and IE 11, and found that Firefox was the only one to limit all entries by default to 150. For the others, I added up to 100,000 entries and saw no limit. ([Here's a demo](http://bl.ocks.org/nolanlawson/e686c8e42c3f2fa7eecd031263053004)).

150 seems like an extremely low limit. Consider my project [marky](https://github.com/nolanlawson/marky), which attempts to provide a sugar API on top of `performance.measure()`, but because it adds two marks and a measure (I do this for maximum debuggability in Chrome Dev Tools, Edge F12, and Windows Performance Analyzer), it's effectively limited to 50 entries in Firefox.

Of course you can increase the limit with `setResourceTimingBufferSize()`, but this still seems like it could cause compatibility issues for Firefox, since many developers may skip this step. Maybe it would be prudent to increase the limit in the spec itself, to something more forgiving like 10,000?

**Comment by igrigorik** [comment]
> Maybe it would be prudent to increase the limit in the spec itself, to something more forgiving like 10,000?

We could, but I also think we want to encourage use of PerformanceObserver's instead of perpetuating the buffer model.. a lower cap on the buffer is a good incentive to switch. That said, we won't be able to eliminate the buffer entirely either -- see https://github.com/w3c/performance-timeline/issues/56#issuecomment-268922807. My proposal would be to evaluate the limit with respect to "is it large enough to buffer records emitted for before onload event has finished executed", and after that we want to nudge folks to use PerfObserver.

Looking at the latest HTTP Archive crawl...

![image](https://cloud.githubusercontent.com/assets/10652/21550950/b33764ac-cdcb-11e6-91e6-17127c04a4f7.png)

^ does suggest that we should consider raising it.

**Comment by nolanlawson** [comment]
> We could, but I also think we want to encourage use of PerformanceObserver's instead of perpetuating the buffer model…

In the case of `marky`, I actually initially tried to implement it using PerformanceObserver (with a fallback), but the result was [a pretty displeasing API](https://github.com/nolanlawson/marky/blob/1895ca1e23b4c835751b81d5c483f6a77242eb08/README.md#asynchronous-measurements) from the user's POV, because everything needed to be asynchronous. (Correct me if there's an easier way! :smiley:)

I definitely think PerformanceObserver has a place, but based on your data it feels like 500 or 1000 would be a more reasonable limit. Might be good to ping Gecko folks, though, since compatibility could also figure into their decision (e.g. they might just raise their own limit without changing the spec).

**Comment by igrigorik** [comment]
Which part is displeasing? I guess I need to understand the use case you're targeting first..

**Comment by nicjansma** [comment]
@nolanlawson @igrigorik I'm slightly confused, because we're talking about two different APIs here (UserTiming vs. ResourceTiming).

* ResourceTiming has a _suggested_ limit of [150 entries](https://www.w3.org/TR/resource-timing-2/#extensions-performance-interface).  IIRC all browsers implementing ResourceTiming today follow this limit.  You can increase the buffer using `setResourceTimingBufferSize()`, and I agree that we may want to increase this limit. (can we use this issue to discuss this?)

On the other hand:

* UserTiming does not mention a buffer limit anywhere in the [v1](https://www.w3.org/TR/user-timing/) or [v2](https://www.w3.org/TR/user-timing-2/) specs, and this is the first I've heard (or seen from your demo!) of any browser implementing a limit.

Personally, I don't think UserTiming _should_ have a max buffer size, or need to be adjusted via a new `setUserTimingBufferSize()` API, as UserTiming is (generally) 100% developer-controlled (unless third-party scripts are dropping marks).

Are these just Firefox implementation bugs?

* Firefox having a 150 UserTiming mark limit
* Firefox's UserTiming limit size controlled via `setResourceTimingBufferSize`

**Comment by nolanlawson** [comment]
@igrigorik 

> Which part is displeasing?

The asynchronous API was a bit hard to work with, e.g. `mark.stop().then(entry => {})`, because I had to wait for PerformanceObserver before resolving the Promise. This is a bit orthogonal to my other points, though. :)

@nicjansma 

> Are these just Firefox implementation bugs?

Ahhh I think you might be right, because the spec does say this only applies to Resource Timing, not User Timing. Firefox's behavior appears to be that it limits _all entry_ types to 150. I'll file a Bugzilla.

**Comment by nolanlawson** [comment]
Filed [Bugzilla #1331135](https://bugzilla.mozilla.org/show_bug.cgi?id=1331135)

**Comment by nolanlawson** [comment]
As for the "displeasing" comment, I opened a new issue: https://github.com/w3c/resource-timing/issues/91 :smiley:

**Comment by nicjansma** [comment]
Thanks @nolanlawson 

Since this Issue is so nicely named, could we continue the discussion here about increasing the [recommended limit](https://www.w3.org/TR/resource-timing-2/#extensions-performance-interface) from 150 entries to a larger number?

(I may have missed a recent call where this was discussed)

**Comment by igrigorik** [comment]
We didn't take it up on last call -- ran out of time. Next week! In the
meantime, would love to hear any proposals.. :)

**Comment by nicjansma** [comment]
Based on [httparchive](http://httparchive.org/about.php#bigquery) data (`2016_11_15_pages` as later runs seem incomplete?), we see results with values from 1 up to 2,819 requests:

* avg: 105
* median: 80
* 75th: 134
* 90th: 209
* 95th: 273
* 98th: 374
* 99th: 466

Based on this, I think a limit of 250 or 300 resources would be very reasonable for capturing ~95% of websites.

(also considering many requests may be happening in IFRAMEs that will have their own buffer)

**Comment by igrigorik** [comment]
I'm wondering if we should push it higher.. 500, or so. Let's discuss on the call tomorrow.

**Comment by nolanlawson** [comment]
Just did a quick test of how Edge 14, Firefox 51, and Chrome 56 actually handle this:

- **Edge**: exposes `setResourceTimingBufferSize()` but doesn't implement, user timing entries are unlimited
- **Chrome**: user timing entries are unlimited, calling `setResourceTimingBufferSize()` does not limit user timings
- **Firefox**: user timing entries are capped to 150 by default, calling `setResourceTimingBufferSize()` sets the limit for user timings (i.e. either increasing them or decreasing them)

So effectively Edge and Chrome have the same behavior (w.r.t. user timings) whereas Firefox stands out.

Tests to reproduce:

- [add 100000 marks, see what happens](http://bl.ocks.org/nolanlawson/raw/e686c8e42c3f2fa7eecd031263053004/)
- [same as above, but call `setResourceTimingBufferSize(100)` first](http://bl.ocks.org/nolanlawson/raw/182875bd41f7ce7fb7d6a93b9a6b84d5/)

**Comment by igrigorik** [comment]
@nolanlawson Safari [added user UT](https://developer.apple.com/safari/technology-preview/release-notes/) recently. Can we add it to your test?

Stepping back.. per UT spec both Edge and Chrome are broken and FF is correct. We should figure out what behavior we actually want/need here.

**Comment by nicjansma** [comment]
I feel like I'm missing something -- there is no buffer specified for UserTiming, right?  Only ResourceTiming?

FF is applying the ResourceTiming buffer limit to UserTiming, which I think is incorrect.

**Comment by igrigorik** [comment]
@nicjansma doh, you're right.. I'm looking at RT repo, but we're talking about UT. Nevermind, there is no limit on UT - all good. FF behavior is a bug.

**Comment by gaearon** [comment]
As a library (React), is there any downside at all to immediately clearing our UT marks? From the chat, I got the impression that people should use observers anyway, and with observers buffer availability is a non-issue.

**Comment by nicjansma** [comment]
@gaearon The only thing when clearing UT marks as a library is to specifically clear the mark names you've emitted (`.clearMarks("mylibrary:mark")`) instead of all of them (`.clearMarks()`) so you're not stomping on other UT consumers.

There's an open issue [here](https://github.com/w3c/user-timing/issues/24) that would be great to have your feedback on, as a library developer.

**Comment by clarkbw** [comment]
FYI [bug 1159003](https://bugzilla.mozilla.org/show_bug.cgi?id=1159003) has landed and today's [Nightly](https://nightly.mozilla.org) no longer has the 150 limit.

**Comment by igrigorik** [comment]
@clarkbw awesome, thanks for the heads up!

**Comment by jjinux** [comment]
Thanks, guys. This was biting us in production at Udemy.

**Comment by igrigorik** [comment]
Courtesy of @nicjansma: https://nicj.net/resourcetiming-visibility-third-party-scripts-ads-and-page-weight/: 

> In our crawl of the Alexa Top 1000, we find that 14.5% of sites exceed 150 resources in the main frame, while only 15% of those sites had called setResourceTimingBufferSize() to ensure all resources were captured.

**Comment by nicjansma** [comment]
Yeah I'm actually surprised that number isn't higher than 14.5%.

In our RUM data, we often see a much higher _overall_ ResourcTiming entry count, but that's because we're crawling all same-origin IFRAMEs and combining the results.  When you limit it to _just_ entries generated by the main frame, it's only ~14.5% of Alexa Top 1000 sites that have more than 150 resources.  The large number of pages we see with more RT entries probably have several IFRAMEs loading a ton of resources (I'm looking at you, ads).

I still think it'd be wise to increase the _suggested_ default limit to more than 150.

I now also think my [previous comment](https://github.com/w3c/resource-timing/issues/89#issuecomment-278214137) isn't an accurate representation, since HttpArchive data shows all frames (same- and cross- origin too).

**Comment by igrigorik** [comment]
> I still think it'd be wise to increase the suggested default limit to more than 150.

👍

**Comment by yoavweiss** [comment]
Closed by #155
