### ISSUE TITLE
Missing TAO tests

### ISSUE THREAD

**Issue by igrigorik** [w3c/resource-timing#92]
Feedback from L1 review:

> It appears that Timing-Allow-Origin was not tested.  I think the implementation report is incomplete without tests for that feature.

Great catch, we should definitely add this!

**Comment by JosephPecoraro** [comment]
There are also no tests for the Performance Timeline extensions (such as `setResourceTimingBufferSize` and the `onresourcetimingbufferfull` event).

Having just modernized WebKit's Resource Timing implementation I added a bunch of tests which I intend to upstream. Look for any tests and resources with the `rt-` prefix:
https://trac.webkit.org/browser/trunk/LayoutTests/imported/w3c/web-platform-tests/resource-timing

Namely `rt-cors.html` and `rt-performance-extensions.html`.

I was dragging my feet a bit because:

* Testing for some RT2 features like `workerStart` means some browsers fail checks early. Wasn't sure if I should mitigate this myself or just put the tests in as in.
* All of these tests use PerformanceObserver (PT2) to gather entries instead of requiring that the entry be added before the resource's onload event (which may not even be possible). Some browsers had difficulty with this, which somewhat breaks tests.
* Tests use random URLs to avoid caches. However sometimes failures output the random URL. This means that if a browser fails a test there may be dynamic failing results. This makes simple expectations difficult. I wasn't sure if I should try to rework that or not.
* More complex TAO tests are possible. I believe Mozilla had some that ensured properly zero'd or valid values when redirecting through allowed and disallowed origins. I only have FIXMEs for such tests.
* Differences between browsers made me limit some of the tests. Things like media resource loading where browsers behave differently. 404/502 which the spec says "May" be included does not lend itself to tests. And admittedly fringe cases, but these are the kinds of things that should be tested.

**Comment by plehegar** [comment]
@JosephPecoraro this seems great feedback for PT2 and I think your tests ought to be looked at by the group. It sounds like the spec leaves a lot of things unspecified and it makes it harder to use.

**Comment by igrigorik** [comment]
@JosephPecoraro there is an open [PR-in-progress for TAO tests](https://github.com/w3c/web-platform-tests/pull/5117). Would appreciate another pair of eyes on it!

> Testing for some RT2 features like workerStart means some browsers fail checks early. Wasn't sure if I should mitigate this myself or just put the tests in as in.

Right, this is an L2 feature. The WPT process doesn't accommodate different levels very well (or, at all, actually). This is an ongoing problem, which I'm not sure what to do about. /cc @rbyers

> All of these tests use PerformanceObserver (PT2) to gather entries instead of requiring that the entry be added before the resource's onload event (which may not even be possible). Some browsers had difficulty with this, which somewhat breaks tests.

Makes sense, as we're then coupling PT2 and RT2. We probably shouldn't do that and try to isolate dependencies as much as possible.

> Tests use random URLs to avoid caches. However sometimes failures output the random URL. This means that if a browser fails a test there may be dynamic failing results. This makes simple expectations difficult. I wasn't sure if I should try to rework that or not.

It does make life harder, ideally.. rework.

> Differences between browsers made me limit some of the tests. Things like media resource loading where browsers behave differently. 404/502 which the spec says "May" be included does not lend itself to tests. And admittedly fringe cases, but these are the kinds of things that should be tested.

Any chance you could summarize the above into a list of tests that are either failing or missing, and open a new issue so we can track it separately from the TAO bits?

**Comment by igrigorik** [comment]
Tests landed (thanks @siusin!) in https://github.com/w3c/web-platform-tests/pull/5117.
