### ISSUE TITLE
Clarify whether UA can clear the buffer under memory pressure

### ISSUE THREAD

**Issue by spanicker** [w3c/resource-timing#94]
The spec says "The user agent may choose to limit how many resources are included as PerformanceResourceTiming objects in the Performance Timeline"

However it is not clear (to me) whether this applies to the default buffer size, or the user agent can choose to clear the buffer when needed. Please clarify.

For background, see: https://crbug.com/685452 for an example where 16k objects (FB is setting buffer to 100k) are bloating memory.

**Comment by yoavweiss** [comment]
Maybe we should add a return value to `setResourceTimingBufferSize()` that'd enable browsers to refuse certain buffer sizes?

At the same time, one can argue that apps can buffer entries externally without any memory limits, so why limit them internally?

**Comment by n8schloss** [comment]
So on Facebook we're using a fairly large buffer because there are times when we want to ensure that we're capturing *all* events within a certain time window. We're going to make a change to clear out the buffer of everything older than a specified time limit every so often, but it'd be nice (and probably more performant) if the api just supported this natively. This way the cleanup could only happen if it was actually needed.

**Comment by yoavweiss** [comment]
Let's discuss on the webperf issue triage call. It's not clear to me if UAs actually want to enforce such limits.

**Comment by toddreifsteck** [comment]
This is a general question regarding buffers of various Performance Timeline items. Moving to Performance Timeline.

This could be achieved by any UA by firing the onbufferfull event allowing the web site to pull events BEFORE clearing the buffer. Because this behavior may not be handled by web sites, it would need to be specced clearly and may need some outreach to sites such as Facebook @n8schloss 

Opening https://github.com/w3c/performance-timeline/issues/101 to trace this issue on timeline
